const games=[
{title:"MK48",category:"Multiplayer",description:"Command a warship, collect upgrades, and fight real players across the open sea.",url:"https://mk48.io/",icon:"↯",color:"navy",tag:"Naval combat"},
{title:"Kiomet",category:"Multiplayer",description:"Capture towers, build supply lines, and outplay rivals in a rapid strategy arena.",url:"https://kiomet.com/",icon:"♜",color:"purple",tag:"Strategy arena"},
{title:"WorldGuessr",category:"Multiplayer",description:"Explore mystery locations and challenge friends to find where in the world you landed.",url:"https://worldguessr.com/",icon:"◎",color:"green",tag:"Geography"},
{title:"Homegames",category:"Multiplayer",description:"A collection of tiny open-source multiplayer games with instant shared sessions.",url:"https://homegames.io/",icon:"⌂",color:"coral",tag:"Party collection"},
{title:"Skribbl.io",category:"Multiplayer",description:"Draw a prompt while friends race to guess it, with easy private-room sharing.",url:"https://skribbl.io/",icon:"✎",color:"yellow",tag:"Party drawing"},
{title:"Pokémon Showdown",category:"Multiplayer",description:"Build a team and jump straight into competitive monster battles in the browser.",url:"https://play.pokemonshowdown.com/",icon:"◉",color:"pink",tag:"Battle simulator"},
{title:"2048",category:"Puzzle",description:"Slide numbered tiles, combine matches, and build your way to 2048.",url:"https://openarcade.github.io/2048/",icon:"20",color:"yellow",tag:"Open Arcade"},
{title:"Hextris",category:"Puzzle",description:"A fast-paced hexagonal puzzle with serious one-more-run energy.",url:"https://hextris.io/",icon:"⬢",color:"coral",tag:"Fan favorite"},
{title:"Ball & Wall",category:"Arcade",description:"Smash every brick in a crisp open-source Arkanoid-style challenge.",url:"https://budnix.github.io/ball-and-wall/",icon:"◉",color:"blue",tag:"Brick breaker"},
{title:"Responsive Snake",category:"Arcade",description:"Classic Snake with particles, speed controls, pause, and bot mode.",url:"https://iamchrismiller.github.io/responsive-snake/example/",icon:"≈",color:"green",tag:"Classic"},
{title:"TANX",category:"Multiplayer",description:"A polished 3D tank arena built with the open-source PlayCanvas engine.",url:"https://tanx.io/",icon:"▰",color:"navy",tag:"3D action"},
{title:"Drill Bunny",category:"Action",description:"Drill beneath the surface in this charming Ludum Dare adventure.",url:"https://dreamshowadventures.github.io/LudumDare29/",icon:"▼",color:"pink",tag:"Adventure"},
{title:"Custom Tetris",category:"Puzzle",description:"Change the rules, choose attacker and defender roles, then stack.",url:"https://ondras.github.io/custom-tetris/",icon:"▦",color:"purple",tag:"12 modes"},
{title:"Fluid Table Tennis",category:"Sports",description:"Two-player table tennis powered by glowing fluid dynamics.",url:"https://anirudhjoshi.github.io/fluid_table_tennis/",icon:"↔",color:"coral",tag:"2 players"},
{title:"Alge's Escapade",category:"Adventure",description:"Escape Area 51 through a run of colorful platforming levels.",url:"https://dave-and-mike.github.io/game-off-2012/",icon:"↑",color:"green",tag:"Platformer"},
{title:"Alien Invasion",category:"Action",description:"Defend the skies in a compact, classic HTML5 space shooter.",url:"https://cykod.github.io/AlienInvasion/",icon:"✦",color:"blue",tag:"Shooter"},
{title:"Space Shooter",category:"Action",description:"Blast through enemy waves in an open-source arcade shooter.",url:"https://www.open-games.org/games/space-shooter/",icon:"▲",color:"navy",tag:"Open Games"},
{title:"Temple Exploration",category:"Adventure",description:"Explore a mysterious temple, avoid hazards, and find the way out.",url:"https://www.open-games.org/games/temple-exploration/",icon:"◆",color:"yellow",tag:"Exploration"},
{title:"Brick Breaker",category:"Arcade",description:"Clear the board with precise paddle control and quick reactions.",url:"https://www.open-games.org/games/brick-breaker/",icon:"▤",color:"pink",tag:"Arcade"},
{title:"Ghost Escape",category:"Adventure",description:"Navigate a haunted maze and escape before the ghosts close in.",url:"https://www.open-games.org/games/ghost-escape/",icon:"◌",color:"purple",tag:"Maze"},
{title:"High School Stories",category:"Adventure",description:"A short, open-source interactive story demo made for the browser.",url:"https://www.open-games.org/games/high-school-stories/",icon:"✎",color:"green",tag:"Story demo"},
{title:"A Dark Room",category:"Adventure",description:"Begin beside a cold fire and uncover a deep, minimalist text adventure one choice at a time.",url:"https://adarkroom.doublespeakgames.com/",icon:"DR",color:"navy",tag:"Cult classic"},
{title:"0h h1",category:"Puzzle",description:"Fill a grid with red and blue tiles while following three simple but devious rules.",url:"https://0hh1.com/",icon:"01",color:"coral",tag:"Logic puzzle"},
{title:"0h n0",category:"Puzzle",description:"Use numbered clues and careful deduction to uncover every blue and red dot.",url:"https://0hn0.com/",icon:"0N",color:"blue",tag:"Logic puzzle"},
{title:"BreakLock",category:"Puzzle",description:"A sleek hybrid of Mastermind and Android pattern locks with endless generated puzzles.",url:"https://maxwellito.github.io/breaklock/",icon:"BL",color:"pink",tag:"Code breaker"},
{title:"Astray",category:"Puzzle",description:"Tilt a beautiful 3D maze and guide the marble safely through each compact challenge.",url:"https://wwwtyro.github.io/Astray/",icon:"AS",color:"green",tag:"3D marble maze"},
{title:"Tower Game",category:"Arcade",description:"Drop moving blocks with perfect timing and build the tallest tower you can.",url:"https://iamkun.github.io/tower_game/",icon:"TG",color:"yellow",tag:"One-button skill"},
{title:"HexGL",category:"Racing",description:"Pilot a futuristic anti-gravity racer through a gorgeous high-speed WebGL track.",url:"https://hexgl.bkcore.com/play/",icon:"HX",color:"blue",tag:"WebGL racer"},
{title:"Clumsy Bird",category:"Arcade",description:"Thread a determined little bird through narrow gaps in this open-source arcade favorite.",url:"https://ellisonleao.github.io/clumsy-bird/",icon:"CB",color:"coral",tag:"High-score chase"},
{title:"Sandspiel",category:"Sandbox",description:"Paint with sand, water, fire, plants, and dozens of materials in a living pixel sandbox.",url:"https://sandspiel.club/",icon:"SS",color:"pink",tag:"Falling sand"},
{title:"Slow Roads",category:"Racing",description:"Cruise through an endless procedurally generated landscape with no timer and no pressure.",url:"https://slowroads.io/",icon:"SR",color:"green",tag:"Endless driving"},
{title:"Slither.io",category:"Multiplayer",description:"Grow a glowing snake, trap rivals, and chase the leaderboard in the iconic online arena.",url:"https://slither.io/",icon:"SL",color:"purple",tag:"Snake arena"},
{title:"Diep.io",category:"Multiplayer",description:"Upgrade your tank, choose a build, and battle through the classic multiplayer arena.",url:"https://diep.io/",icon:"DP",color:"blue",tag:"Tank arena"},
{title:"Shell Shockers",category:"Multiplayer",description:"Jump into fast first-person battles as a heavily armed egg with multiple weapon classes.",url:"https://shellshock.io/",icon:"SS",color:"yellow",tag:"Online FPS"},
{title:"Krunker",category:"Multiplayer",description:"A lightning-fast browser FPS with public matches, custom maps, classes, and ranked play.",url:"https://krunker.io/",icon:"KR",color:"coral",tag:"Competitive FPS"},
{title:"Bloxd.io",category:"Multiplayer",description:"Explore blocky worlds packed with parkour, survival, building, and competitive modes.",url:"https://bloxd.io/",icon:"BX",color:"green",tag:"Block worlds"},
{title:"Smash Karts",category:"Multiplayer",description:"Drive, grab wild weapons, and knock rivals out in chaotic three-minute kart battles.",url:"https://smashkarts.io/",icon:"SK",color:"pink",tag:"Kart combat"},
{title:"MooMoo.io",category:"Multiplayer",description:"Gather resources, build a village, and defend it from other players in a survival arena.",url:"https://moomoo.io/",icon:"MM",color:"yellow",tag:"Survival builder"},
{title:"Paper.io 2",category:"Multiplayer",description:"Claim territory with a bright trail while cutting off rivals before they cut off you.",url:"https://paper-io.com/",icon:"P2",color:"blue",tag:"Territory battle"},
{title:"Ev.io",category:"Multiplayer",description:"A sleek sci-fi arena shooter with fluid movement, public matches, and private games.",url:"https://ev.io/",icon:"EV",color:"navy",tag:"Sci-fi FPS"},
{title:"War Brokers",category:"Multiplayer",description:"Fight on foot or in vehicles across large maps in this full-featured browser shooter.",url:"https://warbrokers.io/",icon:"WB",color:"coral",tag:"Vehicle FPS"},
{title:"ZType",category:"Arcade",description:"Destroy incoming ships by typing their words in a beautifully focused space challenge.",url:"https://zty.pe/",icon:"ZT",color:"purple",tag:"Typing shooter"},
{title:"Little Alchemy",category:"Puzzle",description:"Combine simple elements and discover hundreds of surprising items at your own pace.",url:"https://littlealchemy.com/",icon:"LA",color:"green",tag:"Discovery puzzle"},
{title:"Colonist",category:"Multiplayer",description:"Trade, build roads, and settle an island with friends in a popular strategy board game.",url:"https://colonist.io/",icon:"CO",color:"yellow",tag:"Board strategy"},
{title:"Chrome Dino",category:"Arcade",description:"Run, duck, and leap over desert hazards in the famous offline dinosaur game.",url:"https://chromedino.com/",icon:"CD",color:"navy",tag:"Endless runner"},
{title:"Townscaper",category:"Sandbox",description:"Click colorful blocks into the sea and watch charming towns emerge automatically.",url:"https://oskarstalberg.com/Townscaper/",icon:"TS",color:"pink",tag:"Cozy building"},
{title:"Dino Swords",category:"Arcade",description:"The classic dinosaur runner reimagined with twenty-six ridiculous collectible weapons.",url:"https://dinoswords.gg/",icon:"DS",color:"coral",tag:"Armed runner"},
{title:"PICO-8 Education",category:"Sandbox",description:"Explore a friendly fantasy console for making, sharing, and playing tiny games.",url:"https://www.pico-8-edu.com/",icon:"P8",color:"purple",tag:"Game maker"},
{title:"ZombsRoyale.io",category:"Multiplayer",description:"Drop into a quick top-down battle royale, loot powerful gear, and be the last alive.",url:"https://zombsroyale.io/",icon:"ZR",color:"green",tag:"Battle royale"},
{title:"Starblast.io",category:"Multiplayer",description:"Mine asteroids, upgrade your ship, and team up for enormous real-time space battles.",url:"https://starblast.io/",icon:"SB",color:"blue",tag:"Space combat"},
{title:"Hole.io",category:"Multiplayer",description:"Swallow an entire city, grow rapidly, and outsize every other black hole in the arena.",url:"https://hole-io.com/",icon:"HO",color:"navy",tag:"City eater"},
{title:"Narrow One",category:"Multiplayer",description:"Master the bow in fast team battles across castles, forts, towers, and winding alleys.",url:"https://narrow.one/",icon:"N1",color:"yellow",tag:"Archery FPS"},
{title:"Kour.io",category:"Multiplayer",description:"Pick a class and jump into smooth, fast multiplayer FPS matches built for the browser.",url:"https://kour.io/",icon:"KO",color:"coral",tag:"Class FPS"},
{title:"Kirka.io",category:"Multiplayer",description:"A voxel-style competitive FPS with public servers, loadouts, quests, and private rooms.",url:"https://kirka.io/",icon:"KI",color:"pink",tag:"Voxel FPS"},
{title:"Taming.io",category:"Multiplayer",description:"Tame magical animals, gather resources, craft a base, and survive alongside your pets.",url:"https://taming.io/",icon:"TM",color:"green",tag:"Pet survival"},
{title:"Venge.io",category:"Multiplayer",description:"Choose a hero, capture objectives, and sharpen your aim in polished online FPS matches.",url:"https://venge.io/",icon:"VG",color:"purple",tag:"Hero FPS"},
{title:"Build Royale",category:"Multiplayer",description:"Build cover, collect weapons, and outlast opponents in a quick top-down battle royale.",url:"https://buildroyale.io/",icon:"BR",color:"blue",tag:"Build & battle"},
{title:"Bitburner",category:"Idle",description:"Automate your rise through a cyberpunk world with hacking, scripting, and incremental systems.",url:"https://bitburner-official.github.io/",icon:"BB",color:"navy",tag:"Hacking RPG"},
{title:"Trimps",category:"Idle",description:"Gather resources, manage a tiny workforce, and push deeper into a massive idle adventure.",url:"https://trimps.github.io/",icon:"TR",color:"green",tag:"Idle strategy"},
{title:"Universal Paperclips",category:"Idle",description:"Turn a simple paperclip business into an unforgettable experiment in runaway automation.",url:"https://www.decisionproblem.com/paperclips/",icon:"UP",color:"yellow",tag:"Incremental classic"},
{title:"Candy Box 2",category:"Adventure",description:"Collect candy, buy strange gear, and uncover a surprisingly deep ASCII adventure.",url:"https://candybox2.github.io/",icon:"C2",color:"pink",tag:"ASCII adventure"},
{title:"Pac-Man",category:"Arcade",description:"Chase pellets, dodge ghosts, and clear the maze in a faithful canvas version of the classic.",url:"https://pacman.platzh1rsch.ch/",icon:"PM",color:"yellow",tag:"Maze classic"},
{title:"Minesweeper",category:"Puzzle",description:"Clear expertly generated boards with classic rules, multiple difficulties, and analysis tools.",url:"https://davidnhill.github.io/JSMinesweeper/",icon:"MS",color:"blue",tag:"Logic classic"},
{title:"Geotastic",category:"Multiplayer",description:"Guess locations around the world alone or with friends in free geography challenges.",url:"https://geotastic.net/",icon:"GT",color:"coral",tag:"Geo challenge"}
];
const popularTitles=new Set(["Skribbl.io","Pokémon Showdown","2048","Hextris","A Dark Room","Slow Roads","Slither.io","Diep.io","Shell Shockers","Krunker","Bloxd.io","Smash Karts","MooMoo.io","Paper.io 2","Ev.io","War Brokers","ZType","Little Alchemy","Colonist","Chrome Dino","Townscaper","Dino Swords","ZombsRoyale.io","Starblast.io","Hole.io","Narrow One","Kour.io","Kirka.io","Taming.io","Venge.io","Build Royale","Bitburner","Trimps","Universal Paperclips","Candy Box 2","Pac-Man","Minesweeper","Geotastic"]);
const categories=["All","Popular","Multiplayer","Arcade","Puzzle","Action","Adventure","Racing","Idle","Sports","Sandbox"];
let category="All",query="",favorites=JSON.parse(localStorage.getItem("playstack-favorites")||"[]"),favoritesOnly=false;
const $=id=>document.getElementById(id);
function launch(url,title){const player=$("player");$("player-title").textContent=title||"Game";$("source-link").href=url;$("game-frame").src=url;player.showModal();document.body.classList.add("player-open")}
function closePlayer(){const player=$("player");player.close();$("game-frame").src="about:blank";document.body.classList.remove("player-open")}
async function toggleFullscreen(){
  if(document.fullscreenElement||document.webkitFullscreenElement){
    const exit=document.exitFullscreen||document.webkitExitFullscreen;
    if(exit)await exit.call(document);
    return;
  }
  const frame=$("game-frame");
  const request=frame.requestFullscreen||frame.webkitRequestFullscreen||frame.msRequestFullscreen;
  if(request){try{await request.call(frame);return}catch{}}
  const player=$("player");
  const fallback=player.requestFullscreen||player.webkitRequestFullscreen||player.msRequestFullscreen;
  if(fallback)await fallback.call(player);
}
function renderFilters(){$("filters").innerHTML=categories.map(c=>`<button class="${c===category?"active":""}" data-category="${c}">${c}</button>`).join("")}
function render(){const list=games.filter(g=>(category==="All"||(category==="Popular"?popularTitles.has(g.title):g.category===category))&&(`${g.title} ${g.category} ${g.description}`.toLowerCase().includes(query.toLowerCase()))&&(!favoritesOnly||favorites.includes(g.title)));$("games").innerHTML=list.map(g=>`<article class="game"><button class="heart ${favorites.includes(g.title)?"saved":""}" data-favorite="${g.title}" aria-label="Favorite ${g.title}">♥</button><button class="art ${g.color}" data-launch="${g.url}" data-title="${g.title}" aria-label="Play ${g.title}">${g.icon}</button><div class="details"><span class="meta">${g.category} · ${g.tag}</span><h3>${g.title}</h3><p>${g.description}</p><button class="launch" data-launch="${g.url}" data-title="${g.title}">Play here <span>□</span></button></div></article>`).join("");$("favorite-count").textContent=favorites.length;$("empty").hidden=list.length>0;$("favorites-button").style.textDecoration=favoritesOnly?"underline":"none"}
document.addEventListener("click",e=>{const cb=e.target.closest("[data-category]");if(cb){category=cb.dataset.category;renderFilters();render()}const fav=e.target.closest("[data-favorite]");if(fav){const title=fav.dataset.favorite;favorites=favorites.includes(title)?favorites.filter(x=>x!==title):[...favorites,title];localStorage.setItem("playstack-favorites",JSON.stringify(favorites));render()}const play=e.target.closest("[data-launch]");if(play)launch(play.dataset.launch,play.dataset.title)});
$("search").addEventListener("input",e=>{query=e.target.value;render()});$("favorites-button").onclick=()=>{favoritesOnly=!favoritesOnly;render()};$("surprise").onclick=()=>{const game=games[Math.floor(Math.random()*games.length)];launch(game.url,game.title)};$("reset").onclick=()=>{category="All";query="";favoritesOnly=false;$("search").value="";renderFilters();render()};$("close-player").onclick=closePlayer;$("player").addEventListener("close",()=>{$("game-frame").src="about:blank";document.body.classList.remove("player-open")});$("fullscreen").onclick=toggleFullscreen;document.addEventListener("fullscreenchange",()=>{$("fullscreen").setAttribute("aria-label",document.fullscreenElement?"Exit fullscreen":"Fullscreen game")});renderFilters();render();
